# CloudFormation template for Frank secrets
# These secrets are created on deploy - update values via AWS CLI

Parameters:
  App:
    Type: String
  Env:
    Type: String
  Name:
    Type: String

Resources:
  # Secrets Manager secret for Claude credentials
  ClaudeCredentialsSecret:
    Metadata:
      'aws:copilot:description': 'Claude OAuth credentials'
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '/copilot/${App}/${Env}/secrets/claude-credentials'
      Description: Claude OAuth credentials JSON (update after deploy)
      SecretString: '{"placeholder": "run deploy.sh secrets to update"}'
      Tags:
        - Key: copilot-application
          Value: !Ref App
        - Key: copilot-environment
          Value: !Ref Env

  # Secrets Manager secret for GitHub token
  GitHubTokenSecret:
    Metadata:
      'aws:copilot:description': 'GitHub personal access token'
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '/copilot/${App}/${Env}/secrets/github-token'
      Description: GitHub personal access token (update after deploy)
      SecretString: 'placeholder-run-deploy.sh-secrets'
      Tags:
        - Key: copilot-application
          Value: !Ref App
        - Key: copilot-environment
          Value: !Ref Env

  # Policy to allow ECS task to read secrets
  SecretsAccessPolicy:
    Metadata:
      'aws:copilot:description': 'IAM policy for reading secrets'
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: ReadSecrets
            Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource:
              - !Ref ClaudeCredentialsSecret
              - !Ref GitHubTokenSecret

Outputs:
  ClaudeCredentialsSecretArn:
    Description: ARN of Claude credentials secret
    Value: !Ref ClaudeCredentialsSecret
  GitHubTokenSecretArn:
    Description: ARN of GitHub token secret
    Value: !Ref GitHubTokenSecret
  SecretsAccessPolicyArn:
    Description: Policy ARN to attach to task role
    Value: !Ref SecretsAccessPolicy
